#!/bin/bash

sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager
nmtui

# 必要なパッケージのインストール
sudo vi /etc/pacman.conf
sudo pacman -Syu
sudo pacman -S jq wget vivaldi wezterm xorg-xwayland qt5-wayland unzip lightdm lightdm-webkit2-greeter lightdm-webkit-theme-litarvan 

# PlemolJPなど日本語フォントを規定のフォントにする
wget https://github.com/yuru7/PlemolJP/releases/download/v1.6.0/PlemolJP_NF_v1.6.0.zip
unzip PlemolJP_NF_v1.6.0.zip
sudo mv PlemolJP_NF_v1.6.0/PlemolJPConsole_NF /usr/share/fonts/
rm -rf PlemolJP_NF_v1.6.0.zip PlemolJP_NF_v1.6.0
sudo mv local.conf /etc/fonts/local.conf
fc-cache -vf

# 環境変数の設定
mkdir -p $HOME/.config
mkfit -p $HOME/.config/sway
mkdir -p $HOME/.cache
mkdir -p $HOME/.local/share/go
mkdir $HOME/scripts
echo 'export XDG_CONFIG_HOME="${HOME}/.config"' >> $HOME/.profile
echo 'export XDG_CACHE_HOME="${HOME}/.cache"' >> $HOME/.profile
echo 'export XDG_DATA_HOME="${HOME}/.local/share"' >> $HOME/.profile
echo 'export XDG_STATE_HOME="${HOME}/.local/state"' >> $HOME/.profile
echo 'export GOPATH="${XDG_DATA_HOME}/go"' >> $HOME/.profile
echo 'export PATH="${PATH}:${GOPATH}/bin"' >> $HOME/.profile
echo 'export GTK_IM_MODULE=fcitx' >> $HOME/.xprofile
echo 'export QT_IM_MODULE=fcitx' >> $HOME/.xprofile
echo 'export XMODIFIERS=@im=fcitx' >> $HOME/.xprofile
source $HOME/.profile
source $HOME/.xprofile

# swayの設定
cp /etc/sway/config $XDG_CONFIG_HOME/sway/config
cp -r /etc/xdg/waybar $XDG_CONFIG_HOME/
cat config | cat >> $XDG_CONFIG_HOME/sway/config

# lightdmの設定
sudo systemctl enable lightdm
sudo systemctl enable graphical.target
sudo mv sway.desktop  /usr/share/wayland-sessions/
sudo mv swayon /usr/local/bin/
sudo vi /etc/lightdm/lightdm.conf
